name: Deploy OCR Service

on:
  push:
    paths:
      - 'apps/ocr/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIP }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/coco-ocr apps/ocr
      - run: gcloud run deploy coco-ocr \
          --image gcr.io/${{ secrets.GCP_PROJECT }}/coco-ocr \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --cpu 2 --memory 2Gi \
          --set-env-vars OCR_TOKEN=${{ secrets.OCR_SERVICE_TOKEN }}
